# Generated by Django 3.1.4 on 2020-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(max_length=40, related_name='passengers', to='flights.flights'),
        ),
    ]
